services:
  meili:
    image: getmeili/meilisearch:latest
    container_name: meili
    environment:
      MEILI_MASTER_KEY: chiepdepvlsuperkey
    ports:
      - "7700:7700"

  backend:
    image: backend-app
    container_name: backend
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      MEILI_HOST: "https://meili-search-long-water-6444.fly.dev/"
      MEILI_API_KEY: "chiepdepvlsuperkey"
    ports:
      - "8081:8081"
    depends_on:
      - meili
